package it.pagopa.pn.commons.exceptions;

public class PnExceptionsCodes {

    /**
     * codice di errore generico, quando non si sa cosa mettere. Dovrebbe essere usato il meno possibile
    */
    public static final String ERROR_CODE_PN_GENERIC_ERROR = "PN_GENERIC_ERROR";

    // codici legati alla validazione
    public static final String ERROR_CODE_PN_GENERIC_INVALIDPARAMETER = "PN_GENERIC_INVALIDPARAMETER";
    public static final String ERROR_CODE_PN_GENERIC_INVALIDPARAMETER_ASSERTFALSE = "PN_GENERIC_INVALIDPARAMETER_ASSERTFALSE";
    public static final String ERROR_CODE_PN_GENERIC_INVALIDPARAMETER_ASSERTTRUE = "PN_GENERIC_INVALIDPARAMETER_ASSERTTRUE";
    public static final String ERROR_CODE_PN_GENERIC_INVALIDPARAMETER_MAX = "PN_GENERIC_INVALIDPARAMETER_MAX";
    public static final String ERROR_CODE_PN_GENERIC_INVALIDPARAMETER_MIN = "PN_GENERIC_INVALIDPARAMETER_MIN";
    public static final String ERROR_CODE_PN_GENERIC_INVALIDPARAMETER_DIGITS = "PN_GENERIC_INVALIDPARAMETER_DIGITS";
    public static final String ERROR_CODE_PN_GENERIC_INVALIDPARAMETER_FUTURE = "PN_GENERIC_INVALIDPARAMETER_FUTURE";
    public static final String ERROR_CODE_PN_GENERIC_INVALIDPARAMETER_FUTUREORPRESENT = "PN_GENERIC_INVALIDPARAMETER_FUTUREORPRESENT";
    public static final String ERROR_CODE_PN_GENERIC_INVALIDPARAMETER_PAST = "PN_GENERIC_INVALIDPARAMETER_PAST";
    public static final String ERROR_CODE_PN_GENERIC_INVALIDPARAMETER_PASTORPRESENT = "PN_GENERIC_INVALIDPARAMETER_PASTORPRESENT";
    public static final String ERROR_CODE_PN_GENERIC_INVALIDPARAMETER_REQUIRED = "PN_GENERIC_INVALIDPARAMETER_REQUIRED";
    public static final String ERROR_CODE_PN_GENERIC_INVALIDPARAMETER_NULL = "PN_GENERIC_INVALIDPARAMETER_NULL";
    public static final String ERROR_CODE_PN_GENERIC_INVALIDPARAMETER_PATTERN = "PN_GENERIC_INVALIDPARAMETER_PATTERN";
    public static final String ERROR_CODE_PN_GENERIC_INVALIDPARAMETER_SIZE = "PN_GENERIC_INVALIDPARAMETER_SIZE";
    public static final String ERROR_CODE_PN_GENERIC_INVALIDPARAMETER_EMAIL = "PN_GENERIC_INVALIDPARAMETER_EMAIL";
    public static final String ERROR_CODE_PN_GENERIC_INVALIDPARAMETER_NEGATIVE = "PN_GENERIC_INVALIDPARAMETER_NEGATIVE";
    public static final String ERROR_CODE_PN_GENERIC_INVALIDPARAMETER_NEGATIVEORZERO = "PN_GENERIC_INVALIDPARAMETER_NEGATIVEORZERO";
    public static final String ERROR_CODE_PN_GENERIC_INVALIDPARAMETER_POSITIVE = "PN_GENERIC_INVALIDPARAMETER_POSITIVE";
    public static final String ERROR_CODE_PN_GENERIC_INVALIDPARAMETER_POSITIVEORZERO = "PN_GENERIC_INVALIDPARAMETER_POSITIVEORZERO";


}
